pool:
  vmImage: ubuntu-latest
stages:
- stage: ci
  displayName: Continuous Integration
  jobs:
  - job: build
    displayName: Build Project Assets
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - script: |
        dotnet publish \
        --configuration Release \
        --output out \
        -p:PublishSingleFile=true \
        --runtime win-x64 \
        --self-contained
      displayName: Publish Executable
    - script: |
        dotnet pack \
        --output pkg \
        -p:Version=1.0.0
      displayName: Package for NuGet
    - publish: out/Contoso.Spaces.Console.exe
      displayName: Create Executable build artifact 
      artifact: console-exe
    - publish: pkg/Contoso.Spaces.Console.1.0.0.nupkg
      displayName: Create package build artifact
      artifact: nuget-package

